data:
  {
root_path: '/media/datasets/pose_estimation/MSCOCO_2017',
annotation_path: 'data/coco',
num_keypoints: 17
}
params:
  {
      noise_size: 128
  }
train:
  {
    batch_size: 32, #128,
    resolution: 64

  }
model:
  {
    text:
      {
            checkpoint: '/media/datasets_local/posesyn/fasttext/wiki.en.bin'
    },
    gan:
      {
        pose_gen_lr: 0.0004,
        discriminator_lr: 0.0004,
        model_path: '/media/person_image_syn/models/images'
    }
  }

