# for the DF gan framework (file main.py)

CONFIG_NAME: 'coco'

DATASET_NAME: 'coco'
DATA_DIR: '/home/briq/libs/DF-GAN/data/coco'
GPU_ID: 0
WORKERS: 1


B_VALIDATION: True # True for eval  # False for train
loss: 'hinge'

TREE:
    BRANCH_NUM: 1
    BASE_SIZE: 256


TRAIN:
    NF: 32 # default 64
    BATCH_SIZE: 24
    MAX_EPOCH: 121
    NET_G: 'results/test_dfgan'


TEXT:
    EMBEDDING_DIM: 256
    CAPTIONS_PER_IMAGE: 5
    DAMSM_NAME: '/home/briq/libs/DF-GAN/DAMSMencoders/coco/text_encoder100.pth'
